Add data cleaning pipeline
1. Added remove empty lines pipeline
2. Added remove 6th(Location of Breached Information) and 7th(Summary) column pipeline
3. Added remove row with empty row pipeline

diff --git a/preprocess b/preprocess
--- a/preprocess
+++ b/preprocess
@@ -18,6 +18,7 @@ INVALID_ARGUMENTS_EXIT_CODE=1
 FILE_NOT_FOUND_EXIT_CODE=2
 DATA_NOT_FOUND_EXIT_CODE=3
 INVALID_FILE_EXIT_CODE=4
+INVALID_INPUT_EXIT_CODE=5
 
 # Check if the number of arguments is 1. If not, echo the Usage of the command
 if [[ $# -ne 1 ]]; then
@@ -38,10 +39,22 @@ fi
 # Check whether the file is single line or not
 # awk 'NF' "$tsv_file" -> Removes all the empty lines
 # And then check whether the file has single line only which is assumed to be header.
-awk 'NF' "$tsv_file" | awk -f check_single_line.awk || {
+
+non_empty_lines=$(gawk 'NF' "$tsv_file")
+
+# echo $result
+gawk -v INVALID_INPUT_EXIT_CODE=$INVALID_INPUT_EXIT_CODE -v SUCCESS_EXIT_CODE=$SUCCESS_EXIT_CODE -f check_single_line.awk <<<$non_empty_lines || {
     exit_status=$?
-    echo "Invalid File. $tsv_file has just a single line."
+    echo "Invalid File. $tsv_file has just headers in it."
     exit $exit_status
 }
 
-echo "Hey"
+# Remove first line which is header and remove last two columns
+# filtered_data=${gawk -f remove_columns.awk <<<$non_empty_lines}
+
+filtered_data_with_removed_columns=$(gawk -f remove_columns.awk <<<$non_empty_lines)
+
+# echo -e $filtered_data
+# REMOVED DATA WITH EMPTY CELLS
+# gawk -f drop_empty_cell_row.awk <<<$filtered_data_with_removed_columns
+filtered_data_with_removed_empty_cells=$(gawk -f drop_empty_cell_row.awk <<<$filtered_data_with_removed_columns)
